api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "bundle-discount-functionality"
type = "function"
uid = "44c9b9c4-f182-5ebe-c4d4-6816ae2e18e8ad5485d7"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart_lines_discounts_generate_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/bundle-discount-functionality.wasm"
  watch = [ "src/**/*.rs" ]
